### ISSUE TITLE
thank you my savior

### ISSUE THREAD

**Issue by LarBob** [pmarkham/ansible-zone#2]
(Let me preface this by saying sorry for submitting this as an issue. Didn't know how else to contact you.)

Dear Paul,

Thank you for creating the Solaris Zones module for Ansible. My inhumane overseer was whipping me and demanding I rewrite a docker-compose file for straight Ansible, but thanks to you, I rewrote it for Solaris Zones while still being able to use Ansible. Now my overseer is happy with me and I'm happy that all of our servers are now running Solaris.

You are now my one true savior and I have founded a religion in your name that's long overdue.

Sincerely,
Your biggest fan and worshipper

**Comment by pmarkham** [comment]
LarBob,

Thank you for the praise and worship. The 387 commandments on my religion are easy to follow and, as soon as I've finished writing them up, I'll upload a copy to github.

Glad the module is of use to you, make sure you're grabbing the copy that ships with Ansible rather than the one in this repo.

Regards,

Paul
